repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.12
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.3
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.3
  hooks:
    - id: uv-export
- repo: local
  hooks:
    - id: version-sync-check
      name: Check version consistency
      entry: python .hooks/check_versions_match.py
      language: system
      types: [python]